// Command shapegen writes testdata/real-shape from the real ~/dotfiles:
// the tree shape of both packages with every name below the top level
// replaced through one consistent rename map. Dev-only; tests never run it.
//
//	go run ./internal/tools/shapegen [-root ~/dotfiles] [-out testdata/real-shape]
//
// Preserved: directory shape and depth, which package owns each path and
// where the packages overlap, symlinks inside a package (link text remapped
// component by component), the executable bit, and both .stow-local-ignore
// lists with literal names rewritten through the map. Redacted: every name
// except the top-level ones SPEC.md already prints. Contents are never
// read. Review the output with `git diff` before committing; if anything
// looks like a real name, tighten this generator rather than editing the
// output.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// keep is the set of names SPEC.md already prints. They survive at any
// depth; everything else is renamed.
var keep = map[string]bool{
	".config": true, ".claude": true, ".aws": true, ".agents": true, "bin": true,
	".zsh": true, ".nvim": true, ".zshenv": true, ".gitconfig": true,
	"post-pull.sh": true, "fresh-install.sh": true, "README.md": true, "CLAUDE.md": true,
	".envrc": true, ".stow-local-ignore": true, ".gitignore": true, ".gitattributes": true, ".git": true,
	"settings.local.json": true,
}

// genericPatterns are ignore-list regexps with no literal name in them that
// are safe to copy verbatim. Anything else that is not a literal name is
// dropped from the fixture (and reported).
var genericPatterns = map[string]bool{
	`tags.*`: true, `.*\.swp`: true, `.+~`: true, `\.\#.+`: true, `\#.*\#`: true, `.+,v`: true,
}

type entry struct {
	pkg, typ, exec, path, link string
}

type renamer struct {
	names map[string]string
	next  int
}

func (r *renamer) name(real string) string {
	if keep[real] || real == "." || real == ".." || real == "" {
		return real
	}
	if fake, ok := r.names[real]; ok {
		return fake
	}
	r.next++
	fake := fmt.Sprintf("n%d", r.next)
	if strings.HasPrefix(real, ".") {
		fake = "." + fake
	}
	r.names[real] = fake
	return fake
}

func (r *renamer) path(p string) string {
	parts := strings.Split(p, "/")
	for i, part := range parts {
		parts[i] = r.name(part)
	}
	return strings.Join(parts, "/")
}

func main() {
	home, _ := os.UserHomeDir()
	root := flag.String("root", filepath.Join(home, "dotfiles"), "dotfiles root")
	out := flag.String("out", filepath.Join("testdata", "real-shape"), "output directory")
	flag.Parse()

	r := &renamer{names: map[string]string{}}
	var entries []entry
	ignores := map[string][]string{}
	counts := map[string]int{}

	for _, pkg := range []string{"public", "private"} {
		pkgDir := filepath.Join(*root, pkg)
		err := filepath.WalkDir(pkgDir, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if path == pkgDir {
				return nil
			}
			rel, _ := filepath.Rel(pkgDir, path)
			if rel == ".git" {
				return filepath.SkipDir
			}
			if rel == ".stow-local-ignore" {
				lines, err := readIgnore(path, r)
				if err != nil {
					return err
				}
				ignores[pkg] = lines
				return nil
			}
			e := entry{pkg: pkg, path: r.path(rel), exec: "-"}
			switch {
			case d.Type()&fs.ModeSymlink != 0:
				e.typ = "l"
				dest, err := os.Readlink(path)
				if err != nil {
					return err
				}
				e.link = r.path(dest)
			case d.IsDir():
				e.typ = "d"
			default:
				e.typ = "f"
				info, err := d.Info()
				if err != nil {
					return err
				}
				if info.Mode()&0o111 != 0 {
					e.exec = "x"
				}
			}
			counts[pkg+"/"+e.typ]++
			entries = append(entries, e)
			return nil
		})
		if err != nil {
			fmt.Fprintln(os.Stderr, "shapegen:", err)
			os.Exit(1)
		}
	}

	// Real names must not survive anywhere in the output, including in the
	// order entries are written: sort by the fake path.
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].pkg != entries[j].pkg {
			return entries[i].pkg == "public"
		}
		return entries[i].path < entries[j].path
	})

	if err := os.MkdirAll(*out, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "shapegen:", err)
		os.Exit(1)
	}
	var b strings.Builder
	b.WriteString("# Generated by `go run ./internal/tools/shapegen`. Do not edit by hand.\n")
	b.WriteString("# pkg\ttype\texec\tpath\tlink\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "%s\t%s\t%s\t%s", e.pkg, e.typ, e.exec, e.path)
		if e.typ == "l" {
			fmt.Fprintf(&b, "\t%s", e.link)
		}
		b.WriteString("\n")
	}
	if err := os.WriteFile(filepath.Join(*out, "manifest.tsv"), []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "shapegen:", err)
		os.Exit(1)
	}
	for _, pkg := range []string{"public", "private"} {
		file := filepath.Join(*out, pkg+".stow-local-ignore")
		lines, ok := ignores[pkg]
		if !ok {
			_ = os.Remove(file)
			continue
		}
		if err := os.WriteFile(file, []byte(strings.Join(lines, "\n")+"\n"), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "shapegen:", err)
			os.Exit(1)
		}
	}

	keys := make([]string, 0, len(counts))
	for k := range counts {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Printf("%-10s %d\n", k, counts[k])
	}
	fmt.Printf("renamed    %d distinct names\n", len(r.names))
}

var (
	inlineComment = regexp.MustCompile(`\s+#.+`)
	// An unescaped dot is treated as literal: patterns like `post-pull.sh`
	// mean the file, not "any character".
	regexMeta = regexp.MustCompile(`[*+?()\[\]{}|^$\\]`)
)

// readIgnore rewrites one .stow-local-ignore. Blank lines and comments are
// dropped (a comment could say anything). A pattern that is a literal
// name, or a slash-separated path of literal names, goes through the rename
// map; a known generic pattern is kept; anything else is dropped and
// reported on stderr by shape only, never by content.
func readIgnore(path string, r *renamer) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()
	var out []string
	sc := bufio.NewScanner(f)
	lineNo := 0
	for sc.Scan() {
		lineNo++
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		line = inlineComment.ReplaceAllString(line, "")
		if genericPatterns[line] {
			out = append(out, line)
			continue
		}
		var parts []string
		for _, comp := range strings.Split(strings.TrimPrefix(line, "^/"), "/") {
			literal := strings.ReplaceAll(comp, `\.`, ".")
			if regexMeta.MatchString(literal) {
				fmt.Fprintf(os.Stderr, "shapegen: %s:%d: dropped non-literal pattern (%d chars)\n", filepath.Base(path), lineNo, len(line))
				parts = nil
				break
			}
			parts = append(parts, regexp.QuoteMeta(r.name(literal)))
		}
		if parts != nil {
			out = append(out, strings.Join(parts, "/"))
		}
	}
	return out, sc.Err()
}
